
/* define all net board */

/* PE0 - PE7 for keyboad */
#define KEY_GPIO		GPIOE
#define KEY_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOE_CLK_ENABLE

#define KEY_COL1		GPIO_PIN_0
#define KEY_COL2		GPIO_PIN_1
#define KEY_COL3		GPIO_PIN_2
#define KEY_COL4		GPIO_PIN_3
#define KEY_ROW1		GPIO_PIN_4
#define KEY_ROW2		GPIO_PIN_5
#define KEY_ROW3		GPIO_PIN_6
#define KEY_ROW4		GPIO_PIN_7

/* PE8 - PE15 for LCD */
#define LCD_GPIO		GPIOE
#define LCD_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOE_CLK_ENABLE

#define LCD_RS			GPIO_PIN_8
#define LCD_RW			GPIO_PIN_9
#define LCD_EN			GPIO_PIN_10
#define LCD_DB4			GPIO_PIN_11
#define LCD_DB5			GPIO_PIN_12
#define LCD_DB6			GPIO_PIN_13
#define LCD_DB7			GPIO_PIN_14
#define LCD_BACKLIGHT	GPIO_PIN_15


/* SENSORS **/
/* DOOR SENSOR */
#define DOOR1_GPIO	GPIOF
#define DOOR1_PIN		GPIO_PIN_0
#define DOOR1_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE

#define DOOR2_GPIO	GPIOF
#define DOOR2_PIN		GPIO_PIN_1
#define DOOR2_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE

/* WATER POOR SENSOR */
#define WATER_GPIO	GPIOF
#define WATER_PIN		GPIO_PIN_2
#define WATER_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE

/* HUMIDITY SENSORS */
#define HUMI1_CTRL_PWR_GPIO							GPIOF
#define HUMI1_CTRL_PWR_PIN							GPIO_PIN_5
#define HUMI1_CTRL_PWR_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE
#define HUMI1_DATA_GPIO				GPIOF
#define HUMI1_DATA_GPIO_PIN		GPIO_PIN_13
#define HUMI1_DATA_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE

#define HUMI2_CTRL_PWR_GPIO							GPIOF
#define HUMI2_CTRL_PWR_PIN							GPIO_PIN_6
#define HUMI2_CTRL_PWR_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE
#define HUMI2_DATA_GPIO				GPIOF
#define HUMI2_DATA_GPIO_PIN		GPIO_PIN_14
#define HUMI2_DATA_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE

/* other water*/
#define uC_CTRL_ENA_GPIO				GPIOF
#define uC_CTRL_ENA_GPIO_PIN		GPIO_PIN_7
#define uC_CTRL_ENA_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE
#define uC_SFR05_ECHO_GPIO				GPIOF
#define uC_SFR05_ECHO_GPIO_PIN		GPIO_PIN_10
#define uC_SFR05_ECHO_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE
#define uC_SFR05_OUT_GPIO				GPIOF
#define uC_SFR05_OUT_GPIO_PIN		GPIO_PIN_11
#define uC_SFR05_OUT_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE
#define uC_SFR05_TRG_GPIO				GPIOF
#define uC_SFR05_TRG_GPIO_PIN		GPIO_PIN_12
#define uC_SFR05_TRG_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE

/* moving */
#define PIR_TM_208_GPIO				GPIOF
#define PIR_TM_208_GPIO_PIN		GPIO_PIN_8
#define PIR_TM_208_RCC_CLOCK_ENABLE	__HAL_RCC_GPIOF_CLK_ENABLE
#define PIR_KGS_228D_GPIO				GPIOF
#define PIR_KGS_228D_GPIO_PIN		GPIO_PIN_9

